baseURL = 'https://bao2482003.github.io/22DTHC5-6_BaoDG_MBT/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-US'
title = 'Profile'
theme = 'mytheme'
publishDir = 'docs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "Profile"
  description = "Một nhà phát triển ứng dụng web đầy đam mê"
  author = "Dương Gia Bảo"
  favicon = "/favicon.ico"

[params.banner]
  enable = true
  title = "Kỹ Sư phần mềm"
  subtitle = "Lập trình là nghệ thuật biến đổi ý tưởng thành hiện thực!"
  backgroundImages = [
    "images/banner1.jpg",
    "images/banner2.jpg",
    "images/banner3.jpg"
  ]

[params.hero]
  enable = true
  intro = "Xin chào, Tôi tên là"
  title = "Dương Gia Bảo."
  subtitle = "Sinh viên năm tư chuyên ngành Máy học và Ứng dụng. Chào mừng bạn đến với blog của tôi, hi vọng blog của tôi sẽ mang đến nhiều kiến thức cho bạn! ✨"
  content = "Mỗi ngày là 1 cơ hội mới để mình thay đổi cuộc đời mình!"
  image = "/images/hero.png"

[[menu.main]]
  name = "Về tôi"
  url = "/#about"
  weight = 1

[[menu.main]]
  name = "Kinh nghiệm"
  url = "/#experience"
  weight = 2

[[menu.main]]
  name = "Học vấn"
  url = "/#education"
  weight = 3

[[menu.main]]
  name = "Chứng chỉ"
  url = "/#certificates"
  weight = 4

[[menu.main]]
  name = "Liên hệ"
  url = "/#contact"
  weight = 5

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 6

[[menu.main]]
  name = "Thư viện ảnh"
  url = "/#gallery"
  weight = 7
