baseURL = 'https://bao2482003.github.io/22DTHC5-6_BaoDG_MBT/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-US'
title = 'Profile'
theme = 'mytheme'
publishDir = 'docs'

[params]
  title = "Profile"
  description = "Một nhà phát triển ứng dụng web đầy đam mê"
  author = "Dương Gia Bảo"
  favicon = "/favicon.ico"

[params.hero]
  enable = true
  intro = "Xin chào, Tôi tên là"
  title = "Dương Gia Bảo."
  subtitle = "Tôi xây dựng các ứng dụng cho web."
  content = "Tôi là một nhà phát triển ứng dụng web đầy đam mê. Tôi thường sử dụng các công nghệ web hiện đại để xây dựng các trang web có giao diện đẹp mắt, trải nghiệm người dùng tuyệt vời và hoạt động chính xác."
  image = "/images/hero.png"

[[menu.main]]
  name = "Về tôi"
  url = "/#about"
  weight = 1

[[menu.main]]
  name = "Kinh nghiệm"
  url = "/#experience"
  weight = 2

[[menu.main]]
  name = "Học vấn"
  url = "/#education"
  weight = 3

[[menu.main]]
  name = "Dự án"
  url = "/#projects"
  weight = 4

[[menu.main]]
  name = "Thành tựu"
  url = "/#achievements"
  weight = 5

[[menu.main]]
  name = "Liên hệ"
  url = "/#contact"
  weight = 6

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 7

[[menu.main]]
  name = "Thư viện ảnh"
  url = "/#gallery"
  weight = 8
